apiVersion: v1
kind: Service
metadata:
  name: {{ include "mecak8s.brokerFullname" . }}
  labels: {{- include "mecak8s.brokerLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{- include "mecak8s.brokerLabels" . | nindent 4 }}
  ports:
    - {name: public, port: 8443, targetPort: public}
