apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mecak8s.fullname" . }}
  labels: {{- include "mecak8s.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels: {{- include "mecak8s.selectorLabels" . | nindent 6 }}
