provider:
  clientIngressSelectors:
    - namespaceLabels:
        kubernetes.io/metadata.name: execution-qualification
      podLabels:
        app.kubernetes.io/name: mecak8s
  apiServerCIDRs: [172.16.0.0/12]
  dnsCIDRs: [10.96.0.10/32]
networkPolicy:
  workloadProfiles: {}
