#!/bin/sh
set -eu

# Re-exec once with a deliberately small environment. In particular, no
# provider/API credential or ambient kube context can reach any subprocess.
if [ "${MECATL_EXECUTION_QUAL_CLEAN_ENV:-}" != 1 ]; then
  exec env -i \
    HOME="$HOME" USER="${USER:-user}" PATH="$PATH" XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}" \
    DBUS_SESSION_BUS_ADDRESS="${DBUS_SESSION_BUS_ADDRESS:-}" CONTAINER_HOST="${CONTAINER_HOST:-}" DOCKER_HOST="${DOCKER_HOST:-}" \
    TOOLBOX_PATH="${TOOLBOX_PATH:-}" MECATL_EXECUTION_DEV_TOOLBOX="${MECATL_EXECUTION_DEV_TOOLBOX:-}" MECATL_EXECUTION_K8S_TOOLBOX="${MECATL_EXECUTION_K8S_TOOLBOX:-}" \
    MECATL_EXECUTION_QUAL_CLEAN_ENV=1 "$0" "$@"
fi

[ "$#" -eq 0 ] || { echo "usage: $0" >&2; exit 2; }
case "${MECATL_EXECUTION_DEV_TOOLBOX:-}" in ''|dev) ;; *) echo "MECATL_EXECUTION_DEV_TOOLBOX must be empty or dev" >&2; exit 2 ;; esac
case "${MECATL_EXECUTION_K8S_TOOLBOX:-}" in ''|sre) ;; *) echo "MECATL_EXECUTION_K8S_TOOLBOX must be empty or sre" >&2; exit 2 ;; esac
root=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd -P)
cd "$root"
run_id=$(date -u +%Y%m%d%H%M%S)-$$
cluster="mecatl-execution-qual-$run_id"
context="kind-$cluster"
state="$root/.scratch/k8s-execution/$run_id"
kubeconfig="$state/kubeconfig"
mkdir -p "$root/.scratch/k8s-execution"
umask 077
mkdir "$state"
mkdir "$state/pki" "$state/images"
printf 'cluster=%s\ncontext=%s\nkubeconfig=%s\nnamespace=execution-qualification\nowner=%s\ncreated_at=%s\n' \
  "$cluster" "$context" "$kubeconfig" "${USER:-user}" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >"$state/ownership"

# Refuse collisions; never delete or reuse any cluster.
if kind get clusters 2>/dev/null | grep -Fx "$cluster" >/dev/null; then
  echo "qualification cluster already exists: $cluster" >&2
  exit 1
fi
printf '%s\n' "$state" >"$root/.scratch/k8s-execution/current"

export KIND_EXPERIMENTAL_PROVIDER=podman
export KUBECONFIG="$kubeconfig"
printf '{}\n' >"$state/registry-auth.json"
chmod 600 "$state/registry-auth.json"
export REGISTRY_AUTH_FILE="$state/registry-auth.json"

kind create cluster --name "$cluster" --image kindest/node:v1.35.8@sha256:07b2536e30b803ed61d1677a79df6115f798ce64c80f9e22f6ed45afd09323c0 --kubeconfig "$kubeconfig"

dev() {
  if [ -n "$MECATL_EXECUTION_DEV_TOOLBOX" ]; then
    (cd "$root" && toolbox run -c "$MECATL_EXECUTION_DEV_TOOLBOX" "$@")
  else
    (cd "$root" && "$@")
  fi
}
kube() {
  if [ -n "$MECATL_EXECUTION_K8S_TOOLBOX" ]; then
    toolbox run -c "$MECATL_EXECUTION_K8S_TOOLBOX" kubectl --kubeconfig "$kubeconfig" --context "$context" "$@"
  else
    kubectl --kubeconfig "$kubeconfig" --context "$context" "$@"
  fi
}
helm_kube() {
  if [ -n "$MECATL_EXECUTION_K8S_TOOLBOX" ]; then
    toolbox run -c "$MECATL_EXECUTION_K8S_TOOLBOX" helm --kubeconfig "$kubeconfig" --kube-context "$context" "$@"
  else
    helm --kubeconfig "$kubeconfig" --kube-context "$context" "$@"
  fi
}

# Synthetic keys are generated by the fixture only and never printed. Resume
# keeps the original PKI so mounted trust and running identities cannot drift.
if [ ! -s "$state/pki/ca.crt" ]; then
  dev go run -tags kind_execution_e2e ./e2e/k8s_execution/fixture/pki "$state/pki"
fi

# Build the three static Go images in the development toolbox. ko emits a
# content tag; after loading, the fixture resolves the node's actual manifest
# digest and creates a matching digest alias for Kubernetes.
build_ko() {
  package=$1 repo=$2
  dev env KIND_EXPERIMENTAL_PROVIDER=podman KO_DOCKER_REPO="$repo" ko build --local --bare "$package" | tail -n 1
}
provider_tag=$(build_ko ./cmd/mecatl-execution-provider ko.local/mecatl-execution-provider)
agent_tag=$(build_ko ./cmd/mecak8s ko.local/mecak8s)
oidc_tag=$(dev env KIND_EXPERIMENTAL_PROVIDER=podman GOFLAGS=-tags=kind_execution_e2e KO_DOCKER_REPO=ko.local/mecatl-oidc-fixture ko build --local --bare ./e2e/k8s_execution/fixture/oidcissuer | tail -n 1)

# Resolve the public Go base from the local OCI store, then feed its observed
# digest to the production workload recipe without weakening its pin check.
podman image exists docker.io/library/golang:1.27 || podman pull docker.io/library/golang:1.27 >/dev/null
go_digest=$(podman image inspect docker.io/library/golang:1.27 --format '{{.Digest}}')
go_image="docker.io/library/golang@${go_digest}"
workload_tag="localhost/mecatl-execution-workload:e2e"
podman build --build-arg GO_IMAGE="$go_image" -f "$root/build/execution-workload/Dockerfile" -t "$workload_tag" "$root" >/dev/null

for item in "$provider_tag" "$agent_tag" "$oidc_tag" "$workload_tag"; do
  archive="$state/images/$(printf '%s' "$item" | sha256sum | cut -c1-16).tar"
  podman save "$item" -o "$archive" >/dev/null
  kind load image-archive "$archive" --name "$cluster"
done
node="${cluster}-control-plane"
pin_loaded() {
  tagged=$1
  digest=$(podman exec "$node" ctr -n k8s.io images ls | awk -v ref="$tagged" '$1 == ref {print $3; exit}')
  [ -n "$digest" ] || { echo "loaded image digest unavailable for $tagged" >&2; exit 1; }
  pinned="${tagged%:*}@${digest}"
  podman exec "$node" ctr -n k8s.io images tag "$tagged" "$pinned" >/dev/null
  printf '%s\n' "$pinned"
}
provider_image=$(pin_loaded "$provider_tag")
agent_image=$(pin_loaded "$agent_tag")
oidc_image=$(pin_loaded "$oidc_tag")
workload_image=$(pin_loaded "$workload_tag")
printf 'provider=%s\nagent=%s\noidc=%s\nworkload=%s\ngo_base=%s\n' "$provider_image" "$agent_image" "$oidc_image" "$workload_image" "$go_image" >"$state/images/proof"

kube create namespace execution-qualification --dry-run=client -o yaml | kube apply -f -
kube label namespace execution-qualification pod-security.kubernetes.io/enforce=restricted pod-security.kubernetes.io/audit=restricted pod-security.kubernetes.io/warn=restricted --overwrite

# Kind v0.33 installs its pinned local-path provisioner and default "standard"
# StorageClass as part of cluster creation.

kube -n execution-qualification create secret generic execution-provider-tls \
  --from-file=ca.crt="$state/pki/ca.crt" --from-file=tls.crt="$state/pki/provider.crt" --from-file=tls.key="$state/pki/provider.key" --dry-run=client -o yaml | kube apply -f -
kube -n execution-qualification create secret generic execution-client-tls \
  --from-file=ca.crt="$state/pki/ca.crt" --from-file=tls.crt="$state/pki/mecak8s.crt" --from-file=tls.key="$state/pki/mecak8s.key" --dry-run=client -o yaml | kube apply -f -
kube -n execution-qualification create secret generic execution-intruder-tls \
  --from-file=ca.crt="$state/pki/ca.crt" --from-file=tls.crt="$state/pki/intruder.crt" --from-file=tls.key="$state/pki/intruder.key" --dry-run=client -o yaml | kube apply -f -
kube -n execution-qualification create secret generic execution-grant-key --from-file=key.pem="$state/pki/grant-key.pem" --dry-run=client -o yaml | kube apply -f -
kube -n execution-qualification create secret generic oidc-fixture-identity \
  --from-file=tls.crt="$state/pki/oidc.crt" --from-file=tls.key="$state/pki/oidc.key" --from-file=jwt-key.pem="$state/pki/oidc-jwt-key.pem" --dry-run=client -o yaml | kube apply -f -

sed "s|OIDC_IMAGE|$oidc_image|g" "$root/deploy/mecatl-execution-kind/oidc.yaml" | kube apply -f -
kube -n execution-qualification rollout restart deployment/oidc-issuer
kube -n execution-qualification rollout status deployment/oidc-issuer --timeout=180s

helm_kube upgrade --install mecatl-execution "$root/deploy/helm/mecatl-execution" \
  --namespace execution-qualification \
  --set fullnameOverride=mecatl-execution \
  --set-string provider.image="$provider_image" \
  --set provider.imagePullPolicy=IfNotPresent \
  --set provider.tlsSecretName=execution-provider-tls \
  --set provider.grantSigningSecretName=execution-grant-key \
  --set 'provider.clientURISANs={spiffe://mecatl.test/client/mecak8s,spiffe://mecatl.test/client/intruder}' \
  --set 'provider.ownerAttesterURISANs={spiffe://mecatl.test/client/mecak8s,spiffe://mecatl.test/client/intruder}' \
  --set 'provider.administratorURISANs={spiffe://mecatl.test/client/mecak8s}' \
  --set-string profiles.go.image="$workload_image" \
  --set profiles.go.storageClass=standard --set profiles.go.storageSize=1Gi \
  --set profiles.go.cpuRequest=50m --set profiles.go.memoryRequest=64Mi \
  --set-string profiles.go.cpuLimit=1 --set profiles.go.memoryLimit=512Mi \
  --set profiles.go.maxFileBytes=5242880 --set profiles.go.maxCommandBytes=1048576 \
  --set profiles.go.maxCommandDuration=5m --wait --timeout=4m

kube -n execution-qualification create configmap execution-mock --from-file=mock-script.json="$root/deploy/mecatl-execution-kind/mock-script.json" --dry-run=client -o yaml | kube apply -f -
helm_kube upgrade --install mecak8s "$root/deploy/helm/mecak8s" \
  --namespace execution-qualification -f "$root/deploy/mecatl-execution-kind/mecak8s-values.yaml" \
  --set-string image.repository="${agent_image%@*}" --set-string image.digest="${agent_image#*@}" \
  --wait --timeout=5m
kube -n execution-qualification rollout restart deployment/mecak8s
kube -n execution-qualification rollout status deployment/mecak8s --timeout=240s

dev env -i HOME="$HOME" PATH="$PATH" KUBECONFIG="$kubeconfig" MECATL_KUBE_CONTEXT="$context" MECATL_EXECUTION_QUAL_STATE="$state" \
  go test -tags kind_execution_e2e -count=1 -timeout=15m ./e2e/k8s_execution

echo "qualification cluster retained: $cluster"
echo "kubeconfig: $kubeconfig"
echo "cleanup (requires human confirmation): KIND_EXPERIMENTAL_PROVIDER=podman kind delete cluster --name $cluster"
