apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mecatl-execution.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mecatl-execution.fullname" . }}
rules:
- apiGroups: ["execution.mecatl.dev"]
  resources: ["executionenvironments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["execution.mecatl.dev"]
  resources: ["executionenvironments/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames:
  - {{ printf "%s-security-authority" (include "mecatl-execution.fullname" .) | quote }}
  - "mecatl-execution-profile-allocations"
  verbs: ["get", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mecatl-execution.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "mecatl-execution.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "mecatl-execution.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-%s-profile-preflight" .Release.Namespace (include "mecatl-execution.fullname" .) }}
rules:
- apiGroups: ["node.k8s.io"]
  resources: ["runtimeclasses"]
  resourceNames:
{{- range $name, $profile := .Values.profiles }}
  - {{ $profile.runtimeClassName | quote }}
{{- end }}
  verbs: ["get"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  resourceNames:
{{- range $name, $profile := .Values.profiles }}
  - {{ $profile.storageClass | quote }}
{{- end }}
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-%s-profile-preflight" .Release.Namespace (include "mecatl-execution.fullname" .) }}
subjects:
- kind: ServiceAccount
  name: {{ include "mecatl-execution.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s-%s-profile-preflight" .Release.Namespace (include "mecatl-execution.fullname" .) }}
