/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace.index'
import { Route as WorkspaceChatRouteImport } from './routes/workspace.chat'
import { Route as WorkspaceMemoryRouteImport } from './routes/workspace.memory'
import { Route as WorkspaceSchedulesRouteImport } from './routes/workspace.schedules'
import { Route as WorkspaceSettingsRouteImport } from './routes/workspace.settings'
import { Route as WorkspaceShortcutsRouteImport } from './routes/workspace.shortcuts'
import { Route as WorkspaceSkillsRouteImport } from './routes/workspace.skills'
import { Route as WorkspaceSchedulesScheduleNameRouteImport } from './routes/workspace.schedules_.$scheduleName'
import { Route as WorkspaceSettingsSectionRouteImport } from './routes/workspace.settings_.$section'
import { Route as WorkspaceSkillsViewItemRouteImport } from './routes/workspace.skills_.$view.$item'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceChatRoute = WorkspaceChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceMemoryRoute = WorkspaceMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSchedulesRoute = WorkspaceSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceShortcutsRoute = WorkspaceShortcutsRouteImport.update({
  id: '/shortcuts',
  path: '/shortcuts',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSkillsRoute = WorkspaceSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSchedulesScheduleNameRoute =
  WorkspaceSchedulesScheduleNameRouteImport.update({
    id: '/schedules_/$scheduleName',
    path: '/schedules/$scheduleName',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceSettingsSectionRoute =
  WorkspaceSettingsSectionRouteImport.update({
    id: '/settings_/$section',
    path: '/settings/$section',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceSkillsViewItemRoute = WorkspaceSkillsViewItemRouteImport.update({
  id: '/skills_/$view/$item',
  path: '/skills/$view/$item',
  getParentRoute: () => WorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/workspace/chat': typeof WorkspaceChatRoute
  '/workspace/memory': typeof WorkspaceMemoryRoute
  '/workspace/schedules': typeof WorkspaceSchedulesRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/workspace/shortcuts': typeof WorkspaceShortcutsRoute
  '/workspace/skills': typeof WorkspaceSkillsRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/schedules/$scheduleName': typeof WorkspaceSchedulesScheduleNameRoute
  '/workspace/settings/$section': typeof WorkspaceSettingsSectionRoute
  '/workspace/skills/$view/$item': typeof WorkspaceSkillsViewItemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workspace/chat': typeof WorkspaceChatRoute
  '/workspace/memory': typeof WorkspaceMemoryRoute
  '/workspace/schedules': typeof WorkspaceSchedulesRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/workspace/shortcuts': typeof WorkspaceShortcutsRoute
  '/workspace/skills': typeof WorkspaceSkillsRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/workspace/schedules/$scheduleName': typeof WorkspaceSchedulesScheduleNameRoute
  '/workspace/settings/$section': typeof WorkspaceSettingsSectionRoute
  '/workspace/skills/$view/$item': typeof WorkspaceSkillsViewItemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/workspace/chat': typeof WorkspaceChatRoute
  '/workspace/memory': typeof WorkspaceMemoryRoute
  '/workspace/schedules': typeof WorkspaceSchedulesRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/workspace/shortcuts': typeof WorkspaceShortcutsRoute
  '/workspace/skills': typeof WorkspaceSkillsRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/schedules_/$scheduleName': typeof WorkspaceSchedulesScheduleNameRoute
  '/workspace/settings_/$section': typeof WorkspaceSettingsSectionRoute
  '/workspace/skills_/$view/$item': typeof WorkspaceSkillsViewItemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workspace'
    | '/workspace/chat'
    | '/workspace/memory'
    | '/workspace/schedules'
    | '/workspace/settings'
    | '/workspace/shortcuts'
    | '/workspace/skills'
    | '/workspace/'
    | '/workspace/schedules/$scheduleName'
    | '/workspace/settings/$section'
    | '/workspace/skills/$view/$item'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/workspace/chat'
    | '/workspace/memory'
    | '/workspace/schedules'
    | '/workspace/settings'
    | '/workspace/shortcuts'
    | '/workspace/skills'
    | '/workspace'
    | '/workspace/schedules/$scheduleName'
    | '/workspace/settings/$section'
    | '/workspace/skills/$view/$item'
  id:
    | '__root__'
    | '/'
    | '/workspace'
    | '/workspace/chat'
    | '/workspace/memory'
    | '/workspace/schedules'
    | '/workspace/settings'
    | '/workspace/shortcuts'
    | '/workspace/skills'
    | '/workspace/'
    | '/workspace/schedules_/$scheduleName'
    | '/workspace/settings_/$section'
    | '/workspace/skills_/$view/$item'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/chat': {
      id: '/workspace/chat'
      path: '/chat'
      fullPath: '/workspace/chat'
      preLoaderRoute: typeof WorkspaceChatRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/memory': {
      id: '/workspace/memory'
      path: '/memory'
      fullPath: '/workspace/memory'
      preLoaderRoute: typeof WorkspaceMemoryRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/schedules': {
      id: '/workspace/schedules'
      path: '/schedules'
      fullPath: '/workspace/schedules'
      preLoaderRoute: typeof WorkspaceSchedulesRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/settings': {
      id: '/workspace/settings'
      path: '/settings'
      fullPath: '/workspace/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/shortcuts': {
      id: '/workspace/shortcuts'
      path: '/shortcuts'
      fullPath: '/workspace/shortcuts'
      preLoaderRoute: typeof WorkspaceShortcutsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/skills': {
      id: '/workspace/skills'
      path: '/skills'
      fullPath: '/workspace/skills'
      preLoaderRoute: typeof WorkspaceSkillsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/schedules_/$scheduleName': {
      id: '/workspace/schedules_/$scheduleName'
      path: '/schedules/$scheduleName'
      fullPath: '/workspace/schedules/$scheduleName'
      preLoaderRoute: typeof WorkspaceSchedulesScheduleNameRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/settings_/$section': {
      id: '/workspace/settings_/$section'
      path: '/settings/$section'
      fullPath: '/workspace/settings/$section'
      preLoaderRoute: typeof WorkspaceSettingsSectionRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/skills_/$view/$item': {
      id: '/workspace/skills_/$view/$item'
      path: '/skills/$view/$item'
      fullPath: '/workspace/skills/$view/$item'
      preLoaderRoute: typeof WorkspaceSkillsViewItemRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceChatRoute: typeof WorkspaceChatRoute
  WorkspaceMemoryRoute: typeof WorkspaceMemoryRoute
  WorkspaceSchedulesRoute: typeof WorkspaceSchedulesRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
  WorkspaceShortcutsRoute: typeof WorkspaceShortcutsRoute
  WorkspaceSkillsRoute: typeof WorkspaceSkillsRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceSchedulesScheduleNameRoute: typeof WorkspaceSchedulesScheduleNameRoute
  WorkspaceSettingsSectionRoute: typeof WorkspaceSettingsSectionRoute
  WorkspaceSkillsViewItemRoute: typeof WorkspaceSkillsViewItemRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceChatRoute: WorkspaceChatRoute,
  WorkspaceMemoryRoute: WorkspaceMemoryRoute,
  WorkspaceSchedulesRoute: WorkspaceSchedulesRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
  WorkspaceShortcutsRoute: WorkspaceShortcutsRoute,
  WorkspaceSkillsRoute: WorkspaceSkillsRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceSchedulesScheduleNameRoute: WorkspaceSchedulesScheduleNameRoute,
  WorkspaceSettingsSectionRoute: WorkspaceSettingsSectionRoute,
  WorkspaceSkillsViewItemRoute: WorkspaceSkillsViewItemRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
