apiVersion: v2
name: mecak8s
description: Storage-free mecak8s agents and a singleton mecabroker, backed by externally managed Redis and Kubernetes Leases.
type: application
version: 0.0.40
appVersion: "v0.0.40"
