#!/usr/bin/env python3
"""Generate server flag reference from trusted CLI help in a clean environment."""
import argparse
import os
import re
from pathlib import Path
import shutil
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'user-docs/reference/server-cli.md'

def replace_path(text, path, placeholder):
    # The CLI wraps its own help, so a long path can be split across lines at a
    # hyphen or slash; match it with an optional line break between characters.
    pattern = r'(?:\n[ \t]*)?'.join(re.escape(ch) for ch in path)
    return re.sub(pattern, lambda _: placeholder, text)

def render():
    # Help exits before composition. Strip all operator environment variables;
    # XDG roots point at ignored scratch, preventing operator-config discovery.
    scratch = ROOT / '.scratch/server-cli-reference'
    scratch.mkdir(parents=True, exist_ok=True)
    env = {k: os.environ[k] for k in ('PATH', 'HOME', 'GOPATH', 'GOCACHE', 'GOMODCACHE', 'GOTOOLCHAIN') if k in os.environ}
    env.update(XDG_CONFIG_HOME=str(scratch / 'config'), XDG_STATE_HOME=str(scratch / 'state'), XDG_DATA_HOME=str(scratch / 'data'), XDG_CACHE_HOME=str(scratch / 'cache'), NO_COLOR='1')
    go = shutil.which('go')
    if not go:
        raise RuntimeError('go is required to generate the server CLI reference')
    parts = ['---\ntitle: Server CLI reference\ndescription: Look up the flags registered by mecated and mecak8s.\nsidebar_position: 10\n---\n\n# Server CLI reference\n\n{/* Generated by scripts/server-cli-reference.py. Do not edit by hand. */}\n\nThese inventories come from the flag help registered by each binary. Defaults\nare shown where the CLI prints them; empty values are generally omitted.\nOperator environment overrides are excluded from generation. Environment-backed\ndefaults therefore show their unset form; `<WORKSPACE>`, `<HOME>`, and\n`<XDG_ROOT>` stand for deployment-specific paths when present.\n\nUse [mecated](/operating/mecated.md) or [mecak8s](/operating/mecak8s.md)\nfor deployment workflows. Configuration-file precedence is described in\n[operator settings](/operating/settings.md).\n']
    for title, args in [('mecated serve', ['./cmd/mecated', 'serve', '--help-all']), ('mecak8s', ['./cmd/mecak8s', '--help'])]:
        result = subprocess.run([go, 'run', *args], cwd=ROOT, env=env, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        help_text = '\n'.join(line.rstrip() for line in (result.stdout + result.stderr).expandtabs(8).splitlines()) + '\n'
        # mecak8s currently exits 1 on flag.ErrHelp; accept only that known help path.
        help_requested = title == 'mecak8s' and 'err="flag: help requested"' in help_text
        if (result.returncode and not help_requested) or 'grpc-addr' not in help_text:
            raise RuntimeError(f'{title} help generation failed: {help_text}')
        if help_requested:
            help_text = help_text[:help_text.index('Version:')] + 'Version: mecak8s --version prints the build version and exits.\n'
        help_text = replace_path(help_text, str(scratch), '<XDG_ROOT>')
        help_text = replace_path(help_text, str(ROOT), '<WORKSPACE>')
        if env.get('HOME'):
            help_text = replace_path(help_text, env['HOME'], '<HOME>')
        parts.append(f'\n## {title}\n\n```text\n{help_text.rstrip()}\n```\n')
    return ''.join(parts)

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='verify freshness without modifying output')
    args = parser.parse_args()
    text = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != text:
            print('server CLI reference is stale; run task docs:server-cli', file=sys.stderr)
            return 1
        print('server CLI reference is current')
    else:
        OUTPUT.write_text(text)
    return 0

if __name__ == '__main__':
    sys.exit(main())
