// Package configgen is the SINGLE SOURCE OF TRUTH for the operator settings.yaml
// surface (issue #140). It builds ONE model of the permconfig YAML schema — the
// settings subtrees (permissions, guardrails, posture, learning, models, and peers) — and renders
// BOTH of the operator-facing artifacts from it:
//
//   - the commented settings.yaml SKELETON that `mecated config init` writes, and
//   - the Markdown REFERENCE table (docs/configuration-reference.md).
//
// Because both surfaces walk the SAME model, they cannot drift from each other; and
// because the model is built by reflecting over the permconfig.*Section structs (the
// authoritative strict-decode key list), neither can drift from the code.
//
// # The go/ast boundary
//
// The doc-comment HARVEST (parsing schema.go's field comments via go/ast) happens in
// the build-time generator program ONLY (internal/configgen/cmd/configref). That
// generator emits two COMMITTED artifacts: settings.skeleton.yaml (embedded here and
// served by `config init`) and docs/configuration-reference.md. The shipped mecated
// binary never imports go/ast — it //go:embed's the committed skeleton. The
// artifacts are regenerated by `task docs:configref` and a CI step fails the build
// if they drift.
//
// LAYERING: this is an adapter-side helper. It imports internal/adapter/permconfig
// (the schema it reflects over). It is imported by the generator cmd and by
// cmd/mecated (for the embedded skeleton). It is never imported by the engine, the
// domain, or the port layers.
package configgen

import (
	_ "embed"

	"github.com/stacklok/mecatl/internal/adapter/permconfig"
)

// settingsSkeleton is the committed, generated commented settings.yaml skeleton,
// embedded so `mecated config init` can write it WITHOUT importing go/ast or
// re-running the generator at runtime. It is regenerated by `task docs:configref`
// and guarded against drift in CI.
//
//go:embed settings.skeleton.yaml
var settingsSkeleton string

// Skeleton returns the committed commented settings.yaml skeleton that
// `mecated config init` writes (or prints with --print). It is the embedded
// artifact, NOT a fresh render — the shipped binary stays go/ast-free.
func Skeleton() string {
	return settingsSkeleton
}

// SettingsRelPath is the user-global settings.yaml location relative to the XDG
// config base, re-exported from permconfig so the WRITE path (config init) and the
// READ path (the resolver's loadUserRules) provably resolve the same file. There is
// no second hardcoded "mecatl/settings.yaml" copy.
const SettingsRelPath = permconfig.UserSettingsRelPath
