package configgen

import (
	"fmt"
	"strings"
)

// generatedHeader is the "do not hand-edit" banner both artifacts carry, so a human
// who opens either knows to regenerate via the task target rather than edit in place.
const (
	skeletonHeader = `#| mecatl operator settings.yaml — GENERATED commented skeleton.
#|
#| Written by 'mecated config init'. Place at <XDG_CONFIG_HOME>/mecatl/settings.yaml
#| (default ~/.config/mecatl/settings.yaml) — the operator-tier config the server
#| reads. Uncomment a subtree to enable it; read the inline notes for the EXACT
#| enable semantics of each opt-in feature.
#|
#| NOTE: the values shown below (e.g. default: sonnet, posture: trusted) are
#| ILLUSTRATIVE EXAMPLES, not the built-in defaults. An ABSENT key keeps the
#| harness's built-in default — see the Default column in
#| docs/configuration-reference.md for what each key falls back to when unset.
#|
#| This skeleton is GENERATED from the permconfig YAML schema (the single source of
#| truth). Do not hand-edit the committed copy — run 'task docs:configref'. See
#| docs/configuration-reference.md for the exhaustive key/type/default/tier table.
`
	referenceHeader = `<!-- GENERATED by 'task docs:configref' from the permconfig YAML schema. Do not hand-edit; run the task. -->
# Configuration reference

This page is the **exhaustive, auto-generated reference** for the operator
` + "`settings.yaml`" + ` surface. It is generated from the permconfig YAML schema
(` + "`internal/adapter/permconfig/schema.go`" + `) — the same structs that strictly
parse the file at startup — so it cannot drift from the code.

For the narrative "how do I actually run it" guide and inline examples, see
[the usage guide](usage.md). To scaffold a complete commented file, run
` + "`mecated config init`" + ` (or ` + "`mecated config init --print`" + ` to print it).

The settings file lives at ` + "`<XDG_CONFIG_HOME>/mecatl/settings.yaml`" + `
(default ` + "`~/.config/mecatl/settings.yaml`" + `). The **tier** column records
which configuration tier honours a subtree: ` + "`operator`" + `-tier subtrees are
honoured ONLY from this user-global file + CLI (a project ` + "`.mecatl/settings.yaml`" + `
copy is ignored with a WARN — honouring it would be a security downgrade);
` + "`operator + project`" + ` subtrees may also be set per-project (within the
operator's cap / trust gate).

The **Default** column is the value the harness uses when the key is ABSENT
(` + "`(empty)`" + ` for an unset string, ` + "`(absent)`" + ` for an unset
map/list/sub-block). The example values in the ` + "`config init`" + ` skeleton are
ILLUSTRATIVE, not defaults — an absent key falls back to the Default shown here.
`
)

// RenderSkeleton renders the commented settings.yaml skeleton from the model. The
// output is deterministic (the model's slices are already in a fixed order), so the
// CI diff-guard never flakes.
func RenderSkeleton(m *Model) string {
	var b strings.Builder
	b.WriteString(skeletonHeader)
	for _, st := range m.Subtrees {
		b.WriteString("\n")
		writeSubtreeSkeleton(&b, st)
	}
	return b.String()
}

func writeSubtreeSkeleton(b *strings.Builder, st *Subtree) {
	// Banner: the subtree key + tier + doc + the headline enable note. The banner is
	// PURE DOCUMENTATION (it documents the subtree whether enabled or not), so it uses
	// the "#| " doc-comment marker rather than "# " — this keeps it distinguishable
	// from a commented STRUCTURE line ("# guardrails:") for tooling/tests that strip
	// one comment level to recover the YAML body. (To a human "#|" reads as a comment
	// exactly like "#".)
	fmt.Fprintf(b, "#| === %s === (tier: %s)\n", st.Key, st.Tier)
	writeWrapped(b, "#| ", st.Doc)
	if st.EnableNote != "" {
		writeWrapped(b, "#| ENABLE: ", st.EnableNote)
	}

	// Render the body uncommented into a temp, then (for an opt-in subtree) comment
	// the WHOLE block uniformly. This keeps wrapped continuation lines correctly
	// indented — commenting after rendering, not threading a comment prefix through
	// every recursive write.
	var body strings.Builder
	if st.Scalar {
		f := st.Fields[0]
		fmt.Fprintf(&body, "%s: %s\n", st.Key, placeholder(f))
	} else if st.ListBody {
		// A sequence subtree: render one illustrative list element showing the fields
		// (the first field gets the "- " list marker). The body is a sequence, not a
		// mapping, so the round-trip parse matches the subtree's sequence decoder.
		fmt.Fprintf(&body, "%s:\n", st.Key)
		first := true
		for _, f := range st.Fields {
			if first {
				fmt.Fprintf(&body, "  - %s: %s\n", f.Key, placeholder(f))
				first = false
				continue
			}
			fmt.Fprintf(&body, "    %s: %s\n", f.Key, placeholder(f))
		}
	} else {
		fmt.Fprintf(&body, "%s:\n", st.Key)
		for _, f := range st.Fields {
			writeFieldSkeleton(&body, "  ", f)
		}
	}

	if st.CommentedOut {
		b.WriteString(commentBlock(body.String()))
	} else {
		b.WriteString(body.String())
	}

	// A worked example (realistic values the placeholders can't show) renders as a
	// clearly-labelled trailing comment block — always commented, never part of the
	// live/parsed body.
	if len(st.Example) > 0 {
		b.WriteString("#|\n#| Example:\n")
		for _, line := range st.Example {
			if line == "" {
				b.WriteString("#|\n")
				continue
			}
			fmt.Fprintf(b, "#|   %s\n", line)
		}
	}
}

// commentBlock prefixes every non-empty line of s with "# " (and a blank line stays
// blank), so an opt-in subtree's whole rendered body is commented uniformly.
func commentBlock(s string) string {
	var out strings.Builder
	for _, line := range strings.Split(strings.TrimRight(s, "\n"), "\n") {
		if line == "" {
			out.WriteString("#\n")
			continue
		}
		out.WriteString("# ")
		out.WriteString(line)
		out.WriteString("\n")
	}
	return out.String()
}

func writeFieldSkeleton(b *strings.Builder, indent string, f *Field) {
	writeWrapped(b, indent+"# ", f.Doc)
	if f.EnableNote != "" {
		writeWrapped(b, indent+"# ENABLE: ", f.EnableNote)
	}
	if len(f.Nested) > 0 {
		// A structured sub-mapping: show one example element / the nested keys.
		fmt.Fprintf(b, "%s%s:\n", indent, f.Key)
		// List/element-shaped (e.g. categories) render with a leading "- ".
		if strings.HasPrefix(f.Type, "[]") {
			first := true
			for _, nf := range f.Nested {
				lead := indent + "  "
				if first {
					fmt.Fprintf(b, "%s- %s: %s\n", indent+"  ", nf.Key, placeholder(nf))
					first = false
					continue
				}
				fmt.Fprintf(b, "%s%s: %s\n", lead+"  ", nf.Key, placeholder(nf))
			}
			return
		}
		for _, nf := range f.Nested {
			writeFieldSkeleton(b, indent+"  ", nf)
		}
		return
	}
	fmt.Fprintf(b, "%s%s: %s\n", indent, f.Key, placeholder(f))
}

// placeholder renders a type-shaped example value for a field.
func placeholder(f *Field) string {
	if f.ExampleValue != "" {
		return f.ExampleValue
	}
	switch {
	case f.Type == "bool":
		return "false"
	case f.Type == "int":
		return "0"
	case strings.HasPrefix(f.Type, "[]"):
		return "[]"
	case strings.HasPrefix(f.Type, "map"):
		return "{}"
	default:
		return `""`
	}
}

// writeWrapped writes doc text as one or more comment lines, wrapping to ~88 columns.
// The FIRST line carries prefix (e.g. "  # ENABLE: "); continuation lines carry a
// plain comment prefix at the same indent (no repeated "ENABLE:" label), so a wrapped
// note reads as one annotation rather than N labelled fragments.
func writeWrapped(b *strings.Builder, prefix, text string) {
	text = strings.TrimSpace(text)
	if text == "" {
		return
	}
	const width = 88
	// Continuation prefix: same leading whitespace + "# ", minus any label after "# ".
	cont := contComment(prefix)
	line, lp := prefix, prefix
	for i, word := range strings.Fields(text) {
		if i > 0 && len(line)+1+len(word) > width {
			b.WriteString(strings.TrimRight(line, " "))
			b.WriteString("\n")
			line, lp = cont, cont
		}
		if len(line) > len(lp) {
			line += " "
		}
		line += word
	}
	if strings.TrimSpace(line) != "" {
		b.WriteString(strings.TrimRight(line, " "))
		b.WriteString("\n")
	}
}

// contComment derives the continuation-line prefix from a first-line prefix: keep the
// leading whitespace and the comment marker ("# " or the "#| " doc marker), dropping
// any label (text after the marker). So "  # ENABLE: " -> "  # " and "#| ENABLE: " ->
// "#| ".
func contComment(prefix string) string {
	idx := strings.Index(prefix, "#")
	if idx < 0 {
		return prefix
	}
	marker := "# "
	if strings.HasPrefix(prefix[idx:], "#|") {
		marker = "#| "
	}
	return prefix[:idx] + marker
}

// RenderReference renders the Markdown reference page: a table per subtree plus the
// hand-written flag-driven-features pointer block. Deterministic.
func RenderReference(m *Model) string {
	var b strings.Builder
	b.WriteString(referenceHeader)
	for _, st := range m.Subtrees {
		b.WriteString("\n")
		writeSubtreeReference(&b, st)
	}
	b.WriteString("\n")
	b.WriteString(flagDrivenSection)
	return b.String()
}

func writeSubtreeReference(b *strings.Builder, st *Subtree) {
	fmt.Fprintf(b, "## `%s`\n\n", st.Key)
	fmt.Fprintf(b, "Tier: **%s**\n\n", st.Tier)
	if st.Doc != "" {
		b.WriteString(mdParagraph(st.Doc))
		b.WriteString("\n")
	}
	if st.EnableNote != "" {
		fmt.Fprintf(b, "> **Enable:** %s\n\n", oneLine(st.EnableNote))
	}
	if st.Scalar {
		f := st.Fields[0]
		b.WriteString("| Value | Type | Default | Description |\n")
		b.WriteString("| --- | --- | --- | --- |\n")
		fmt.Fprintf(b, "| `%s` | `%s` | `%s` | %s |\n", st.Key, f.Type, defaultCell(f.Default), oneLine(f.Doc))
		return
	}
	b.WriteString("| Key | Type | Default | Description |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	path := st.Key
	if st.ListBody {
		path = st.Key + "[]"
	}
	for _, f := range st.Fields {
		writeFieldReference(b, path, f)
	}
}

func writeFieldReference(b *strings.Builder, path string, f *Field) {
	full := path + "." + f.Key
	desc := oneLine(f.Doc)
	if f.EnableNote != "" {
		desc += " **Enable:** " + oneLine(f.EnableNote)
	}
	fmt.Fprintf(b, "| `%s` | `%s` | `%s` | %s |\n", full, f.Type, defaultCell(f.Default), desc)
	// A slice-of-struct's children are array ELEMENTS (foo[].bar); a plain nested
	// mapping's children are direct keys (foo.bar).
	childPath := full
	if strings.HasPrefix(f.Type, "[]") {
		childPath = full + "[]"
	}
	for _, nf := range f.Nested {
		writeFieldReference(b, childPath, nf)
	}
}

func defaultCell(d string) string {
	if strings.TrimSpace(d) == "" {
		return "—"
	}
	return d
}

// oneLine collapses a multi-line doc into a single line and escapes the table-cell
// pipe so a description containing `|` cannot break the Markdown table.
func oneLine(s string) string {
	s = strings.Join(strings.Fields(s), " ")
	return strings.ReplaceAll(s, "|", "\\|")
}

// mdParagraph collapses a doc's hard breaks into a single paragraph line.
func mdParagraph(s string) string {
	return strings.Join(strings.Fields(s), " ") + "\n"
}

// flagDrivenSection is the hand-written pointer block (decision 1): the settings.yaml
// reference covers the four permconfig subtrees ONLY; the other operator-facing
// features are wired through CLI flags / their own files, not settings.yaml. This
// block points operators at usage.md + the relevant flags rather than auto-harvesting
// every CLI flag (deliberately rejected).
const flagDrivenSection = "## Flag- / file-configured features (NOT in `settings.yaml`)\n" +
	"\n" +
	"By design, `settings.yaml` covers the four subtrees above. Several other\n" +
	"operator features are configured through **CLI flags** (and, for some, their own\n" +
	"files) rather than this YAML. See the [usage guide](usage.md) §3 (Running the\n" +
	"server) and §6 (Configuration) for the full flag tables; the pointers below are\n" +
	"the starting points:\n" +
	"\n" +
	"| Feature | How it is configured | See |\n" +
	"| --- | --- | --- |\n" +
	"| Soul (operator persona) | `--soul-dir` (+ its own `soul.md` / persona files) | usage.md §6 |\n" +
	"| User-model learning | `--user-model-store` / `--user-model-review` | usage.md §6 |\n" +
	"| Memory | `--memory-store` (+ the per-project `.mecatl/memory.json`) | usage.md §6 |\n" +
	"| Slash commands | `--commands-dir` (+ the command `.md` files) | usage.md §6 |\n" +
	"| Session leasing | `--session-lease-*` | usage.md §3 |\n" +
	"\n" +
	"The model slots / aliases above also have CLI twins (`--model-slot` /\n" +
	"`--model-alias`); the guardrails checker model has `--guardrails-model`; the\n" +
	"router kill-switch has `--subagent-model-router=false`. The CLI flag and the\n" +
	"YAML key are two surfaces for the same setting — see usage.md for precedence.\n"
